name: Linters

on:
  push:
jobs:
  linters:
    name: Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@9b252454a8d70586c4ee7f163bf4bb1e9de3d763 # v2

      - name: Enable binary cache
        uses: cachix/cachix-action@v15
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check EditorConfig
        run: nix-shell --run "editorconfig-checker"

      - name: Check flake8
        run: nix-shell --run "flake8 manual/preprocess.py"

      - name: Check rustfmt
        run: nix-shell --run "cargo fmt --check"
